project_id = "fxiggeohozwjfadxvekb"

[functions."plugin-router"]
verify_jwt = false

# paths are relative to the 'supabase/' folder, so drop the leading supabase/
static_files = [
  "functions/plugin-router/ai-plugin.json",
  "functions/plugin-router/openapi.yaml",
]
