# supabase/config.toml

project_id = "fxiggeohozwjfadxvekb"

[functions."plugin-router"]
verify_jwt  = false
static_files = [
  "supabase/functions/plugin-router/ai-plugin.json",
  "supabase/functions/plugin-router/openapi.yaml",
]
